### ISSUE TITLE
java.io.IOException: Cannot run program "su": error=13, Permission denied

### ISSUE THREAD

**Issue by Yangtingyu** [hqwlkj/flutter_huashi#1]
你好,感谢你的开源,我在使用中遇到了以下报错:

W/System.err(21201): java.io.IOException: Cannot run program "su": error=13, Permission denied
W/System.err(21201):    at java.lang.ProcessBuilder.start(ProcessBuilder.java:983)
W/System.err(21201):    at java.lang.Runtime.exec(Runtime.java:691)
W/System.err(21201):    at java.lang.Runtime.exec(Runtime.java:524)
W/System.err(21201):    at java.lang.Runtime.exec(Runtime.java:421)
W/System.err(21201):    at android_serialport_api.SerialPort.<init>(SerialPort.java:47)
W/System.err(21201):    at com.huashi.otg.sdk.HsSerialPortSDK.init(HsSerialPortSDK.java:38)
W/System.err(21201):    at com.urovo.xbsdk.SerialIDCardUtil.initCom(SerialIDCardUtil.java:97)
W/System.err(21201):    at com.urovo.xbsdk.SerialIDCardUtil.access$200(SerialIDCardUtil.java:13)
W/System.err(21201):    at com.urovo.xbsdk.SerialIDCardUtil$CPUThread.run(SerialIDCardUtil.java:143)
W/System.err(21201): Caused by: java.io.IOException: error=13, Permission denied
W/System.err(21201):    at java.lang.UNIXProcess.forkAndExec(Native Method)
W/System.err(21201):    at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
W/System.err(21201):    at java.lang.ProcessImpl.start(ProcessImpl.java:128)
W/System.err(21201):    at java.lang.ProcessBuilder.start(ProcessBuilder.java:964)
W/System.err(21201):    ... 8 more
D/test    (21201): >>ComApi.init:1
E/HUASHI-CARD(21201): -1
E/HUASHI-CARD(21201): 初始失败

**Comment by hqwlkj** [comment]
这个插件需要使用专用的设备才可以，手机和其他的Android设备都是不可以的。

**Comment by Yangtingyu** [comment]
> 这个插件需要使用专用的设备才可以，手机和其他的Android设备都是不可以的。

您好,我是华视100U 真机,看报错是否需要机子 root.[https://xiudo-shanghai.oss-cn-shanghai.aliyuncs.com/uPic/Screenshot_20210226-115211.png](url)

**Comment by Yangtingyu** [comment]
> 这个插件需要使用专用的设备才可以，手机和其他的Android设备都是不可以的。

您好,我是华视100U 真机,看报错是否需要机子 root?

![Screenshot_20210226-115211](https://user-images.githubusercontent.com/12782796/109445958-b3245180-7a7b-11eb-8fc0-13665798534f.png)

**Comment by hqwlkj** [comment]
`华视100U ` 应该不行的，设备读卡是因为集成了读卡模块，不同的模块有不同的协议，这个不是通用的。 这个需要看看你的读卡器是什么型号的了。

**Comment by hqwlkj** [comment]
目前，我们公司使用的是 ：`T5000` 的设备，
